import { StyleSheet } from "react-native";
import type { AppThemeTokens } from "../context/theme";

export const createStyles = ({ COLORS, RADIUS, SPACING }: AppThemeTokens) => StyleSheet.create({
  container: {
    padding: SPACING.xxl,
    backgroundColor: COLORS.backgroundAlt,
    flexGrow: 1,
    width: "100%",
    maxWidth: 1180,
    alignSelf: "center",
  },
  containerCompact: {
    padding: SPACING.lg,
  },
  toastContainer: {
    alignSelf: "center",
    backgroundColor: COLORS.textPrimary,
    borderRadius: RADIUS.button,
    paddingHorizontal: SPACING.xxl,
    paddingVertical: SPACING.md,
    marginBottom: SPACING.lg,
  },
  toastText: {
    color: COLORS.white,
    fontWeight: "700",
    fontSize: 12,
  },
  habitCelebrateBanner: {
    alignSelf: "center",
    backgroundColor: COLORS.successSoft,
    borderColor: COLORS.success,
    borderWidth: 1,
    borderRadius: RADIUS.button,
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.sm,
    marginBottom: SPACING.md,
  },
  habitCelebrateText: {
    color: COLORS.success,
    fontWeight: "700",
    fontSize: 12,
  },
  title: {
    fontSize: 32,
    fontWeight: "800",
    letterSpacing: -0.4,
    color: COLORS.textPrimary,
  },
  titleCompact: {
    fontSize: 28,
  },
  welcomeText: {
    color: COLORS.textMuted,
    marginBottom: SPACING.xs,
  },
  heroCard: {
    backgroundColor: COLORS.card,
    borderRadius: RADIUS.card,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: SPACING.xl,
    marginTop: SPACING.lg,
    shadowColor: COLORS.black,
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  heroCardCompact: {
    padding: SPACING.lg,
  },
  heroEyebrow: {
    alignSelf: "flex-start",
    marginBottom: SPACING.md,
    color: COLORS.primary,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  heroHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: SPACING.md,
  },
  scoreRingWrap: {
    width: 112,
    height: 112,
    alignItems: "center",
    justifyContent: "center",
  },
  scoreRingChart: {
    borderRadius: 999,
  },
  scoreRingCenter: {
    position: "absolute",
    width: 74,
    height: 74,
    borderRadius: 37,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.card,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  scoreRingValue: {
    color: COLORS.textPrimary,
    fontWeight: "800",
    fontSize: 22,
    lineHeight: 24,
  },
  scoreRingLabel: {
    color: COLORS.textMuted,
    fontSize: 10,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  subtitle: {
    marginTop: SPACING.sm,
    color: COLORS.textMuted,
    marginBottom: SPACING.md,
  },
  progressTrack: {
    marginTop: SPACING.md,
    height: 8,
    borderRadius: 999,
    overflow: "hidden",
    backgroundColor: COLORS.border,
  },
  progressFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: COLORS.primary,
  },
  progressText: {
    marginTop: SPACING.sm,
    color: COLORS.textMuted,
    fontSize: 12,
  },
  positiveDeltaText: {
    marginTop: SPACING.xs,
    color: COLORS.success,
    fontSize: 12,
    fontWeight: "700",
  },
  momentumBanner: {
    marginTop: SPACING.md,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.background,
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.md,
  },
  momentumBannerPositive: {
    borderColor: COLORS.success,
    backgroundColor: COLORS.successSoft,
  },
  momentumBannerText: {
    color: COLORS.textPrimary,
    fontWeight: "700",
    fontSize: 12,
  },
  heroSnapshotRow: {
    flexDirection: "row",
    gap: SPACING.sm,
    marginTop: SPACING.md,
  },
  heroSnapshotCard: {
    flex: 1,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surfaceMuted,
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.md,
  },
  heroSnapshotLabel: {
    color: COLORS.textMuted,
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  heroSnapshotValue: {
    color: COLORS.textPrimary,
    fontSize: 22,
    fontWeight: "800",
  },
  kpiRow: {
    flexDirection: "row",
    gap: SPACING.sm,
    marginTop: SPACING.md,
    marginBottom: SPACING.xl,
    flexWrap: "wrap",
  },
  kpiRowCompact: {
    gap: SPACING.xs,
  },
  kpiCard: {
    flex: 1,
    minWidth: 132,
    backgroundColor: COLORS.card,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.sm,
    alignItems: "flex-start",
  },
  kpiLabel: {
    color: COLORS.textMuted,
    fontSize: 11,
    marginBottom: 2,
  },
  kpiValue: {
    color: COLORS.textPrimary,
    fontWeight: "700",
    fontSize: 20,
  },
  topActionsRow: {
    flexDirection: "row",
    gap: SPACING.md,
    marginBottom: SPACING.xxl,
  },
  topActionsRowCompact: {
    flexDirection: "column",
    gap: SPACING.sm,
    marginBottom: SPACING.xl,
  },
  topActionButton: {
    flex: 1,
    backgroundColor: COLORS.card,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: RADIUS.card,
    paddingVertical: SPACING.lg,
    paddingHorizontal: SPACING.lg,
    shadowColor: COLORS.black,
    shadowOpacity: 0.05,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  topActionButtonCompact: {
    width: "100%",
  },
  topActionText: {
    color: COLORS.textPrimary,
    fontWeight: "700",
    fontSize: 18,
    marginTop: 2,
  },
  topActionKicker: {
    color: COLORS.primary,
    fontWeight: "800",
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  topActionSubtext: {
    marginTop: SPACING.xs,
    color: COLORS.textMuted,
    lineHeight: 18,
    fontSize: 12,
  },
  weeklySummaryCard: {
    marginBottom: SPACING.xxl,
    backgroundColor: COLORS.card,
    borderRadius: RADIUS.card,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: SPACING.xxl,
    shadowColor: COLORS.black,
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  weeklySummaryCardCompact: {
    padding: SPACING.lg,
    marginBottom: SPACING.xl,
  },
  weeklySummaryTitle: {
    color: COLORS.textPrimary,
    fontSize: 16,
    fontWeight: "700",
    marginBottom: SPACING.sm,
  },
  weeklySummaryBody: {
    color: COLORS.textSecondary,
    lineHeight: 20,
  },
  coachingPresetRow: {
    flexDirection: "row",
    gap: SPACING.sm,
    marginBottom: SPACING.md,
  },
  coachingPresetButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: RADIUS.md,
    paddingVertical: SPACING.sm,
    alignItems: "center",
    backgroundColor: COLORS.background,
  },
  coachingPresetButtonActive: {
    borderColor: COLORS.primary,
    backgroundColor: COLORS.primarySoft,
  },
  coachingPresetButtonText: {
    color: COLORS.textMuted,
    fontWeight: "700",
    fontSize: 12,
  },
  coachingPresetButtonTextActive: {
    color: COLORS.primary,
  },
  coachingList: {
    gap: SPACING.sm,
  },
  coachingItem: {
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surfaceMuted,
    padding: SPACING.md,
    gap: SPACING.xs,
  },
  coachingItemTitle: {
    color: COLORS.textPrimary,
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  coachingItemBody: {
    color: COLORS.textSecondary,
    lineHeight: 19,
    fontSize: 13,
  },
  weeklySummaryButton: {
    marginTop: SPACING.md,
    alignSelf: "flex-start",
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.primarySoft,
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.lg,
  },
  weeklySummaryButtonText: {
    color: COLORS.primary,
    fontWeight: "700",
  },
  focusTimerClock: {
    color: COLORS.textPrimary,
    fontWeight: "800",
    fontSize: 30,
    letterSpacing: 1,
  },
  focusProgressTrack: {
    height: 8,
    borderRadius: 999,
    overflow: "hidden",
    backgroundColor: COLORS.border,
    marginTop: SPACING.xs,
  },
  focusProgressFill: {
    height: "100%",
    backgroundColor: COLORS.primary,
    borderRadius: 999,
  },
  focusControlsRow: {
    marginTop: SPACING.sm,
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    flexWrap: "wrap",
  },
  focusInput: {
    minWidth: 72,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.background,
    color: COLORS.textPrimary,
    borderRadius: RADIUS.md,
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.md,
    fontWeight: "700",
  },
  focusPrimaryButton: {
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.primary,
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.lg,
  },
  focusPrimaryButtonText: {
    color: COLORS.white,
    fontWeight: "700",
  },
  focusSecondaryButton: {
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.background,
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.md,
  },
  focusSecondaryButtonText: {
    color: COLORS.textPrimary,
    fontWeight: "700",
    fontSize: 12,
  },
  monthlyStatsGrid: {
    gap: SPACING.sm,
  },
  monthlyStatItem: {
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surfaceMuted,
    padding: SPACING.md,
  },
  improvementUp: {
    color: COLORS.success,
  },
  improvementDown: {
    color: COLORS.danger,
  },
  grid: {
    gap: SPACING.lg,
  },
  blockHeading: {
    color: COLORS.textSecondary,
    fontWeight: "700",
    textTransform: "uppercase",
    fontSize: 12,
    letterSpacing: 0.8,
  },
  card: {
    backgroundColor: COLORS.card,
    borderRadius: RADIUS.card,
    padding: SPACING.xxlPlus,
    borderWidth: 1,
    borderColor: COLORS.border,
    shadowColor: COLORS.black,
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  cardShell: {
    borderRadius: RADIUS.card,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: "600",
  },
  scoreRow: {
    marginTop: SPACING.sm,
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
  },
  cardScore: {
    fontSize: 26,
    fontWeight: "700",
  },
  trendText: {
    fontSize: 14,
    fontWeight: "700",
  },
  cardTarget: {
    marginTop: SPACING.xs,
    color: COLORS.textMuted,
  },
  cardUpdated: {
    marginTop: SPACING.xs,
    color: COLORS.textSubtle,
    fontSize: 12,
  },
  sectionCard: {
    marginTop: SPACING.xxl,
    backgroundColor: COLORS.card,
    borderRadius: RADIUS.card,
    padding: SPACING.xxl,
    borderWidth: 1,
    borderColor: COLORS.border,
    shadowColor: COLORS.black,
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  analyticsBody: {
    marginTop: SPACING.md,
  },
  sectionHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: SPACING.sm,
    gap: SPACING.md,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: COLORS.textPrimary,
  },
  sectionMeta: {
    fontSize: 12,
    color: COLORS.textMuted,
  },
  badgeGrid: {
    gap: SPACING.sm,
  },
  emptyState: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: RADIUS.card,
    backgroundColor: COLORS.surfaceMuted,
    padding: SPACING.lg,
    marginBottom: SPACING.sm,
  },
  emptyStateCompact: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.surfaceMuted,
    padding: SPACING.md,
  },
  emptyStateTitle: {
    color: COLORS.textPrimary,
    fontWeight: "700",
    marginBottom: SPACING.xs,
  },
  emptyStateBody: {
    color: COLORS.textMuted,
    fontSize: 12,
    lineHeight: 18,
  },
  emptyStateButton: {
    marginTop: SPACING.md,
    backgroundColor: COLORS.primary,
    borderRadius: RADIUS.md,
    paddingVertical: SPACING.sm,
    alignItems: "center",
  },
  emptyStateButtonText: {
    color: COLORS.white,
    fontWeight: "700",
  },
  analyticsPreviewCards: {
    marginTop: SPACING.md,
    gap: SPACING.sm,
  },
  previewCard: {
    backgroundColor: COLORS.background,
    borderRadius: RADIUS.card,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: SPACING.lg,
    gap: SPACING.xs,
    minHeight: 72,
    justifyContent: "center",
  },
  previewTitle: {
    color: COLORS.textPrimary,
    fontWeight: "700",
  },
  previewBody: {
    color: COLORS.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  badgeCard: {
    borderRadius: RADIUS.card,
    borderWidth: 1,
    padding: SPACING.lg,
  },
  badgeUnlocked: {
    borderColor: COLORS.success,
    backgroundColor: COLORS.successSoft,
  },
  badgeLocked: {
    borderColor: COLORS.border,
    backgroundColor: COLORS.background,
  },
  badgeTitle: {
    fontWeight: "700",
    color: COLORS.textSecondary,
    marginBottom: SPACING.xs,
  },
  badgeTitleUnlocked: {
    color: COLORS.success,
  },
  badgeDetail: {
    color: COLORS.textMuted,
    fontSize: 12,
  },
  habitSummary: {
    color: COLORS.textMuted,
    fontSize: 12,
    marginBottom: SPACING.md,
  },
  habitList: {
    gap: SPACING.sm,
  },
  weekResetButton: {
    marginTop: SPACING.md,
    alignSelf: "flex-start",
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.danger,
    backgroundColor: COLORS.card,
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.lg,
  },
  weekResetButtonText: {
    color: COLORS.danger,
    fontWeight: "700",
  },
  toggleRow: {
    marginTop: SPACING.md,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.md,
  },
  toggleLabel: {
    flex: 1,
    color: COLORS.textPrimary,
    fontWeight: "600",
  },
  habitItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.md,
    borderRadius: RADIUS.card,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: SPACING.lg,
    backgroundColor: COLORS.background,
  },
  habitItemShell: {
    borderRadius: RADIUS.card,
  },
  habitChecked: {
    borderColor: COLORS.success,
    backgroundColor: COLORS.successSoft,
  },
  habitCheck: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: COLORS.textSubtle,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.white,
  },
  habitCheckActive: {
    borderColor: COLORS.success,
    backgroundColor: COLORS.success,
  },
  habitCheckMark: {
    color: COLORS.white,
    fontSize: 12,
    fontWeight: "700",
  },
  habitLabel: {
    color: COLORS.textPrimary,
    fontWeight: "600",
  },
  habitTextBlock: {
    flex: 1,
  },
  habitStreakText: {
    marginTop: 2,
    color: COLORS.textMuted,
    fontSize: 11,
    fontWeight: "600",
  },
  infoText: {
    marginTop: SPACING.sm,
    color: COLORS.textSecondary,
    lineHeight: 20,
  },
  linkButton: {
    marginTop: SPACING.md,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: SPACING.md,
    backgroundColor: COLORS.background,
  },
  linkButtonText: {
    color: COLORS.textPrimary,
    fontWeight: "600",
  },
  resetButton: {
    marginTop: SPACING.md,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.danger,
    padding: SPACING.md,
    backgroundColor: COLORS.card,
  },
  resetButtonText: {
    color: COLORS.danger,
    fontWeight: "700",
  },
  button: {
    marginTop: SPACING.xxl,
    backgroundColor: COLORS.primary,
    borderRadius: RADIUS.md,
    padding: SPACING.input,
    alignItems: "center",
  },
  buttonText: {
    color: COLORS.white,
    fontWeight: "600",
  },
  secondaryButton: {
    marginTop: SPACING.md,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.primary,
    padding: SPACING.input,
    alignItems: "center",
    backgroundColor: COLORS.card,
  },
  secondaryButtonText: {
    color: COLORS.primary,
    fontWeight: "600",
  },
});
